# Pandas Library

In [1]:
import numpy as np
import pandas as pd

In [8]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [12]:
import pandas as pd

ages = pd.Series([20, 22, 25])

print(ages)

0    20
1    22
2    25
dtype: int64

In [18]:
# 2- Dimentional Dataframes 
data = {
    "Name":["Ali", "Sara", "John"],
    "Age": [28, 22, 24] ,
    "Score": [92, 87, 84]
    }
df = pd.DataFrame(data)

df

   Name  Age  Score
0   Ali   28     92
1  Sara   22     87
2  John   24     84

In [20]:
df['Age']

0    28
1    22
2    24
Name: Age, dtype: int64

In [21]:
df['Name']

0     Ali
1    Sara
2    John
Name: Name, dtype: str

In [23]:
df[['Name', 'Score']]

   Name  Score
0   Ali     92
1  Sara     87
2  John     84

In [24]:
# Select rows 

df.iloc[0]

Name     Ali
Age       28
Score     92
Name: 0, dtype: object

In [26]:
df.iloc[0:3]

   Name  Age  Score
0   Ali   28     92
1  Sara   22     87
2  John   24     84

In [27]:
df.iloc[1]

Name     Sara
Age        22
Score      87
Name: 1, dtype: object

In [28]:
df.loc[1]

Name     Sara
Age        22
Score      87
Name: 1, dtype: object

In [29]:
# Shape of your data

df.shape

(3, 3)

In [32]:
df.head

<bound method NDFrame.head of    Name  Age  Score
0   Ali   28     92
1  Sara   22     87
2  John   24     84>

In [35]:
df.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [36]:
df.dtypes

Name       str
Age      int64
Score    int64
dtype: object

In [37]:
df.head()

   Name  Age  Score
0   Ali   28     92
1  Sara   22     87
2  John   24     84

In [38]:
df.head

<bound method NDFrame.head of    Name  Age  Score
0   Ali   28     92
1  Sara   22     87
2  John   24     84>

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [40]:
df.describe()

             Age      Score
count   3.000000   3.000000
mean   24.666667  87.666667
std     3.055050   4.041452
min    22.000000  84.000000
25%    23.000000  85.500000
50%    24.000000  87.000000
75%    26.000000  89.500000
max    28.000000  92.000000

In [ ]:
# Reading Data

df = pd.read_csv("students.csv")
df = pd.read_excel("students.xlsx")
#saving files
df.to_csv("output.csv", index=False)

In [45]:
#7. Filtering 

# Find students older than 21. 

df[df["Age"] > 21]

   Name  Age  Score
2  John   24     84
1  Sara   22     87
0   Ali   28     92

In [51]:
#Multiple Conditions 

df[df["Age"] > 21 & (df["Score"] > 85)]

#it doesnt drop john with 84 becuse his age is > 21.

   Name  Age  Score
2  John   24     84
1  Sara   22     87
0   Ali   28     92

In [53]:
# wrape each condition in () and then it will be like AND gate option. 

df[(df["Age"] > 21) & (df["Score"] > 85)]

   Name  Age  Score
1  Sara   22     87
0   Ali   28     92

In [56]:
# 8. Adding Columns 

df["Passed"] = df["Score"] >= 80
df

   Name  Age  Score  Passed
2  John   24     84    True
1  Sara   22     87    True
0   Ali   28     92    True

####  Adding rows to the datafram 
The syntax df.loc[len(df)] = ... is a clever trick to add a row to the end of a DataFrame.Here is exactly how it works, broken down piece by piece:The Breakdownlen(df) counts the total number of rows.
- A 0-indexed DataFrame with 2 rows has index labels 0 and 1.For this DataFrame, len(df) returns exactly 2.
- df.loc[...] targets rows by their index label.df.loc[2] looks for a row labeled 2.
- Since index 2 does not exist yet, Pandas creates it.
- The assignment = ['Charlie', 35] fills this new row with your data.

In [101]:
df.loc[len(df)] = ["Ahmad", 25, 88, True]

      Name  Age  Score  Passed
2     John   24     84    True
1     Sara   22     87    True
0      Ali   28     92    True
3    Ahmad   25     88    True
4    Ahmad   25     88    True
5  Jessica   24     95    True
6    Ahmad   25     88    True
7  Jessica   24     95    True

In [102]:
df.loc[len(df)] = {
    "Name": "Jessica",
    "Age": 24,
    "Score": 95, 
    "Passed": True
}
df

      Name  Age  Score  Passed
2     John   24     84    True
1     Sara   22     87    True
0      Ali   28     92    True
3    Ahmad   25     88    True
4    Ahmad   25     88    True
5  Jessica   24     95    True
6    Ahmad   25     88    True
7  Jessica   24     95    True
8  Jessica   24     95    True

In [105]:
new_rows = pd.DataFrame({
    "Name": ["Tom", "Emma"],
    "Age": [23, 21],
    "Score": [80, 92], 
    "Passed": [True, True]
})

df = pd.concat([df, new_rows], ignore_index=True)
df

       Name  Age  Score Passed
0      John   24     84   True
1      Sara   22     87   True
2       Ali   28     92   True
3     Ahmad   25     88   True
4     Ahmad   25     88   True
5   Jessica   24     95   True
6     Ahmad   25     88   True
7   Jessica   24     95   True
8   Jessica   24     95   True
9       Tom   23     80    NaN
10     Emma   21     92    NaN
11      Tom   23     80    NaN
12     Emma   21     92    NaN
13      Tom   23     80   True
14     Emma   21     92   True

In [111]:
df = df.dropna()

In [112]:
df = df.drop_duplicates()
df

       Name  Age  Score Passed
0      John   24     84   True
1      Sara   22     87   True
2       Ali   28     92   True
3     Ahmad   25     88   True
5   Jessica   24     95   True
13      Tom   23     80   True
14     Emma   21     92   True

In [119]:
df.loc[len(df)] = ["Anna", 20, 85, True]
df

       Name  Age  Score Passed
0      John   24     84   True
1      Sara   22     87   True
2       Ali   28     92   True
3     Ahmad   25     88   True
5   Jessica   24     95   True
13      Tom   23     80   True
14     Emma   21     92   True
7      Anna   20     85   True
8      Anna   20     85   True

In [58]:
#9. Sorting

df.sort_values("Score")

#Ascending

   Name  Age  Score  Passed
2  John   24     84    True
1  Sara   22     87    True
0   Ali   28     92    True

In [59]:
#descending
df.sort_values("Score", ascending=False)

   Name  Age  Score  Passed
0   Ali   28     92    True
1  Sara   22     87    True
2  John   24     84    True

In [60]:
# 10. Missing Valuse
#find the null values
df.isnull()

    Name    Age  Score  Passed
2  False  False  False   False
1  False  False  False   False
0  False  False  False   False

In [63]:
#Count them
df.isnull().sum()

Name      0
Age       0
Score     0
Passed    0
dtype: int64

In [64]:
# remove them

df.dropna()

   Name  Age  Score  Passed
2  John   24     84    True
1  Sara   22     87    True
0   Ali   28     92    True

In [66]:
#Replace them
df.fillna(0)

   Name  Age  Score  Passed
2  John   24     84    True
1  Sara   22     87    True
0   Ali   28     92    True

In [69]:
dep_salary = {
    "Department":["Bio", "Bio", "Chem", "Chem"],

    "Salary": [5000, 6000, 7000, 9000]
    }
df_dep = pd.DataFrame(dep_salary)

df_dep

  Department  Salary
0        Bio    5000
1        Bio    6000
2       Chem    7000
3       Chem    9000

In [71]:
# 11. Group By

# This is arguably pandas most powerful feature. 
# Suppose 
''' 
Department   Salary
Bio          5000
Bio          6000
Chem         7000
Chem         9000
'''

df_dep.groupby("Department")["Salary"].mean()

Department
Bio     5500.0
Chem    8000.0
Name: Salary, dtype: float64

In [72]:
# 12. Value Counts

# Count categories.
df_dep["Department"].value_counts()

Department
Bio     2
Chem    2
Name: count, dtype: int64

In [74]:
# 13. Unique Values 
df_dep ["Department"].unique()

<StringArray>
['Bio', 'Chem']
Length: 2, dtype: str

In [75]:
#Number of unique values 
df_dep ["Department"].nunique()

2

In [79]:
# 14. Renaming columns
df.rename(columns={"Score": "Marks"})

   Name  Age  Marks  Passed
2  John   24     84    True
1  Sara   22     87    True
0   Ali   28     92    True

In [81]:
#dropping Columns 
df.drop(columns = ["Age"])

   Name  Score  Passed
2  John     84    True
1  Sara     87    True
0   Ali     92    True

In [82]:
#16. Basic Statistics 
df["Score"].mean()

np.float64(87.66666666666667)

In [83]:
df["Score"].median()

np.float64(87.0)

In [84]:
df["Score"].max()

np.int64(92)

In [85]:
df["Score"].min()

np.int64(84)

In [86]:
df["Score"].std()

np.float64(4.041451884327381)

In [87]:
# 17. Applying Functions 
df["Age"].apply(lambda x: x+1)

2    25
1    23
0    29
Name: Age, dtype: int64

In [96]:
# 18. Boolean Indexing 
high = df["Score"] > 90
high

2    False
1    False
0     True
Name: Score, dtype: bool

In [97]:
df[high]

  Name  Age  Score  Passed
0  Ali   28     92    True

In [ ]:
#19 Resetting index 
df.reset_index(drop=True)

#useful after filtering or sorting

In [43]:
#20 Method Chaining 
# instead of writing this 

df = df.dropna()
df = df.sort_values("Score")
df = df.head(10)

In [44]:
# write this 

df = (
    df 
    .dropna()
    .sort_values("Score")
    .head(10)
)

#Cleaner and easier to read.

## A Mental Model That Will Save You Time

- When using Pandas, ask yourself these four questions:

- How do I load the data? (read_csv, read_excel)
- How do I inspect it? (head, info, describe, shape)
- How do I select or transform it? (column selection, loc, iloc, filtering, apply)
- How do I summarize it? (groupby, value_counts, mean, describe)

- Most data analysis tasks follow this cycle repeatedly.

## A Practical Learning Path (Especially for Bioinformatics)

- Given your background in microbiology and bioinformatics, I suggest learning Pandas in this order:

    - Creating Series and DataFrame
    - Reading CSV/Excel files
    - Inspecting data (head, info, describe)
    - Selecting rows and columns (loc, iloc)
    - Filtering data
    - Handling missing values
    - Sorting and adding columns
    - Grouping and aggregation (groupby)
    - Merging and joining datasets
    - Working with dates and times
    - Reshaping data (pivot, melt)
    - Applying custom functions and optimizing performance

- Once you're comfortable with these, you'll be able to manipulate gene expression tables, sequencing metadata, antimicrobial susceptibility results, and other biological datasets efficiently.

In [11]:
dates = pd.date_range('20260730', periods = 6) 
dates

DatetimeIndex(['2026-07-30', '2026-07-31', '2026-08-01', '2026-08-02',
               '2026-08-03', '2026-08-04'],
              dtype='datetime64[us]', freq='D')